{% set name = "dicfg" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dicfg-{{ version }}.tar.gz
  sha256: 165bc7d2a25bd4e3e861d12247f40ca395fe330f06e07695a3fc50d29ad40254

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - PyYaml >=5.4.1
    - pip
  run:
    - python >=3.8
    - PyYaml >=5.4.1

test:
  imports:
    - dicfg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dicfg/
  summary: Dicfg is a configuration system that supports dependency injection via object interpolation in config files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martvanrijthoven
